spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/growthnote?serverTimezone=Asia/Seoul
    username: root
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
  main:
    allow-bean-definition-overriding: true

